const stubItem = {
  id: 20759221,
  node_id: "MDEwOlJlcG9zaXRvcnkyMDc1OTIyMQ==",
  name: "ChaZD",
  full_name: "ververcpp/ChaZD",
  private: false,
  owner: {
    login: "ververcpp",
    id: 980232,
    node_id: "MDQ6VXNlcjk4MDIzMg==",
    avatar_url: "https://avatars.githubusercontent.com/u/980232?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ververcpp",
    html_url: "https://github.com/ververcpp",
    followers_url: "https://api.github.com/users/ververcpp/followers",
    following_url:
      "https://api.github.com/users/ververcpp/following{/other_user}",
    gists_url: "https://api.github.com/users/ververcpp/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ververcpp/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ververcpp/subscriptions",
    organizations_url: "https://api.github.com/users/ververcpp/orgs",
    repos_url: "https://api.github.com/users/ververcpp/repos",
    events_url: "https://api.github.com/users/ververcpp/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ververcpp/received_events",
    type: "User",
    site_admin: false,
  },
  html_url: "https://github.com/ververcpp/ChaZD",
  description: "ChaZD 查字典，简洁易用的英汉字典Chrome扩展程序，支持划词哦:)",
  fork: false,
  url: "https://api.github.com/repos/ververcpp/ChaZD",
  forks_url: "https://api.github.com/repos/ververcpp/ChaZD/forks",
  keys_url: "https://api.github.com/repos/ververcpp/ChaZD/keys{/key_id}",
  collaborators_url:
    "https://api.github.com/repos/ververcpp/ChaZD/collaborators{/collaborator}",
  teams_url: "https://api.github.com/repos/ververcpp/ChaZD/teams",
  hooks_url: "https://api.github.com/repos/ververcpp/ChaZD/hooks",
  issue_events_url:
    "https://api.github.com/repos/ververcpp/ChaZD/issues/events{/number}",
  events_url: "https://api.github.com/repos/ververcpp/ChaZD/events",
  assignees_url:
    "https://api.github.com/repos/ververcpp/ChaZD/assignees{/user}",
  branches_url:
    "https://api.github.com/repos/ververcpp/ChaZD/branches{/branch}",
  tags_url: "https://api.github.com/repos/ververcpp/ChaZD/tags",
  blobs_url: "https://api.github.com/repos/ververcpp/ChaZD/git/blobs{/sha}",
  git_tags_url: "https://api.github.com/repos/ververcpp/ChaZD/git/tags{/sha}",
  git_refs_url: "https://api.github.com/repos/ververcpp/ChaZD/git/refs{/sha}",
  trees_url: "https://api.github.com/repos/ververcpp/ChaZD/git/trees{/sha}",
  statuses_url: "https://api.github.com/repos/ververcpp/ChaZD/statuses/{sha}",
  languages_url: "https://api.github.com/repos/ververcpp/ChaZD/languages",
  stargazers_url: "https://api.github.com/repos/ververcpp/ChaZD/stargazers",
  contributors_url: "https://api.github.com/repos/ververcpp/ChaZD/contributors",
  subscribers_url: "https://api.github.com/repos/ververcpp/ChaZD/subscribers",
  subscription_url: "https://api.github.com/repos/ververcpp/ChaZD/subscription",
  commits_url: "https://api.github.com/repos/ververcpp/ChaZD/commits{/sha}",
  git_commits_url:
    "https://api.github.com/repos/ververcpp/ChaZD/git/commits{/sha}",
  comments_url:
    "https://api.github.com/repos/ververcpp/ChaZD/comments{/number}",
  issue_comment_url:
    "https://api.github.com/repos/ververcpp/ChaZD/issues/comments{/number}",
  contents_url: "https://api.github.com/repos/ververcpp/ChaZD/contents/{+path}",
  compare_url:
    "https://api.github.com/repos/ververcpp/ChaZD/compare/{base}...{head}",
  merges_url: "https://api.github.com/repos/ververcpp/ChaZD/merges",
  archive_url:
    "https://api.github.com/repos/ververcpp/ChaZD/{archive_format}{/ref}",
  downloads_url: "https://api.github.com/repos/ververcpp/ChaZD/downloads",
  issues_url: "https://api.github.com/repos/ververcpp/ChaZD/issues{/number}",
  pulls_url: "https://api.github.com/repos/ververcpp/ChaZD/pulls{/number}",
  milestones_url:
    "https://api.github.com/repos/ververcpp/ChaZD/milestones{/number}",
  notifications_url:
    "https://api.github.com/repos/ververcpp/ChaZD/notifications{?since,all,participating}",
  labels_url: "https://api.github.com/repos/ververcpp/ChaZD/labels{/name}",
  releases_url: "https://api.github.com/repos/ververcpp/ChaZD/releases{/id}",
  deployments_url: "https://api.github.com/repos/ververcpp/ChaZD/deployments",
  created_at: "2014-06-12T07:51:25Z",
  updated_at: "2023-04-25T16:00:43Z",
  pushed_at: "2018-06-07T07:27:58Z",
  git_url: "git://github.com/ververcpp/ChaZD.git",
  ssh_url: "git@github.com:ververcpp/ChaZD.git",
  clone_url: "https://github.com/ververcpp/ChaZD.git",
  svn_url: "https://github.com/ververcpp/ChaZD",
  homepage: "",
  size: 8048,
  stargazers_count: 447,
  watchers_count: 447,
  language: "JavaScript",
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  has_discussions: false,
  forks_count: 191,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 54,
  license: null,
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: [],
  visibility: "public",
  forks: 191,
  open_issues: 54,
  watchers: 447,
  default_branch: "master",
  score: 1,
};
